### ISSUE TITLE
For none tech users 

### ISSUE THREAD

**Issue by Fher01** [scroll-tech/contribute-to-scroll#55]
Hello. How hard is scroll gonna be for people that is not familiar with blockchain technology. I believe that mass adoption of this tech only will come if regular users can join in an easy way.

**Comment by Turupawn** [comment]
Hello, thanks for your interest in Scroll. I'll be closing this issue due to being offtopic. This place is for contributions to dev tools, integrations ans skunkworks. For future issues please refer to the [Contributing](https://github.com/scroll-tech/contribute-to-scroll/blob/main/CONTRIBUTING.md) guide.

That being said, I'll share my thoughs about this topic. So Scroll is going to have the same UX as Ethereum but faster and cheaper. This means Scroll will face the sames challenges and will have the same improvements as Ethereum all along the way. Currently we have many challenges but there are many solutions being worked on such account abstraction that should improve the UX in multiple ways. For futures inquires the Scroll Discord should be able to provide a better answer, you should be able to join soon since we're working on expanding the amount of members since we reached the maximum amount.
